### ISSUE TITLE
Implement the ArgMax function

### ISSUE THREAD

**Issue by mathias-nillion** [NillionNetwork/nada-by-example#15]
### Description
Implement the ArgMax function efficiently over an array of `SecretInteger`s

### Use Case
The argmax is a commonly used data wrangling operation. Efficiently implementing it from scratch is a bit non-trivial. Therefore, we want to provide this functionality as a built-in feature of [nada-numpy](https://github.com/NillionNetwork/nada-numpy)

### Specific Requirements
Here is an example program that uses argmax.
```
DIM = 10

def argmax(array: na.NadaArray):
    # compute the argmax
    return result

def nada_main():
    party1 = Party(name="Party1")

    array = na.array([DIM], party1, "array", SecretInteger)

    result = argmax(array)

    return na.output(result, party1, "argmax")
```

**Comment by jimouris** [comment]
Closed by https://github.com/NillionNetwork/nada-by-example/pull/22
