### ISSUE TITLE
Implement cube root in nada

### ISSUE THREAD

**Issue by Davetbutler** [NillionNetwork/nada-by-example#5]
### Description
Implement a nada program that computes the cube root of an inputted SecretInteger

### Use Case
This is a commonly used math function, and thus we should have an example for others to use rather than write the nada program from scratch.

### Specific Requirements
The nada program should have one party, whose input is a SecretInteger and output the square root (or an approximation of the square root) of that number.

```
def nada_main():

    party1 = Party(name="Party1")

    num = SecretInteger(Input(name="num", party=party1))

    # compute the cube root

    return [Output(square_root, "square_root", party1)]
```

**Comment by jimouris** [comment]
Closed by https://github.com/NillionNetwork/nada-by-example/pull/21
